{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import requests\n",
    "from splinter import Browser\n",
    "import pandas as pd\n",
    "import pymongo\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "url = 'https://mars.nasa.gov/news/'\n",
    "response = requests.get(url)\n",
    "soup = BeautifulSoup(response.text, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<!DOCTYPE html>\n",
      "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\n",
      " <head>\n",
      "  <link href=\"//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\"/>\n",
      "  <title>\n",
      "   Valles Marineris Hemisphere Unenhanced | USGS Astrogeology Science Center\n",
      "  </title>\n",
      "  <meta content=\"Mosaic of the Valles Marineris hemisphere of Mars projected into point perspective, a view similar to that which one would…\" name=\"description\"/>\n",
      "  <meta content=\"USGS,Astrogeology Science Center,Cartography,Geology,Space,Geological Survey,Mapping\" name=\"keywords\"/>\n",
      "  <meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\"/>\n",
      "  <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n",
      "  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1\" name=\"viewport\"/>\n",
      "  <meta content=\"x61hXXVj7wtfBSNOPnTftajMsZ5yB2W-qRoyr7GtOKM\" name=\"google-site-verification\"/>\n",
      "  <!--<link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,bold\"/>-->\n",
      "  <link href=\"/css/main.css\" media=\"screen\" rel=\"stylesheet\"/>\n",
      "  <link href=\"/css/print.css\" media=\"print\" rel=\"stylesheet\"/>\n",
      "  <!--[if lt IE 9]>\n",
      "\t\t\t<script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\n",
      "\t\t\t<script src=\"/js/respond.min.js\"></script>\n",
      "\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/ie.css\"/>\n",
      "                        <script>\n",
      "                          document.createElement('header');\n",
      "                          document.createElement('nav');\n",
      "                          document.createElement('section');\n",
      "                          document.createElement('article');\n",
      "                          document.createElement('aside');\n",
      "                          document.createElement('footer');\n",
      "                          document.createElement('hgroup');\n",
      "                        </script>\n",
      "                  <![endif]-->\n",
      "  <link href=\"/favicon.ico\" rel=\"icon\" type=\"image/x-ico\"/>\n",
      " </head>\n",
      " <body id=\"splashy\">\n",
      "  <header>\n",
      "   <h1>\n",
      "    Astrogeology Science Center\n",
      "   </h1>\n",
      "   <a href=\"http://www.usgs.gov\">\n",
      "    <img alt=\"USGS: Science for a Changing World\" class=\"logo\" height=\"70\" src=\"/images/usgs_logo_main_2x.png\" width=\"180\"/>\n",
      "   </a>\n",
      "  </header>\n",
      "  <div class=\"wrapper\">\n",
      "   <nav>\n",
      "    <a href=\"#\" id=\"nav-toggle\" title=\"Navigation Menu\">\n",
      "     Menu\n",
      "    </a>\n",
      "    <ul class=\"dropdown dropdown-horizontal\" id=\"yw0\">\n",
      "     <li>\n",
      "      <a href=\"/\">\n",
      "       Home\n",
      "      </a>\n",
      "     </li>\n",
      "     <li>\n",
      "      <a href=\"/about\">\n",
      "       About\n",
      "      </a>\n",
      "      <ul>\n",
      "       <li>\n",
      "        <a href=\"/about/careers\">\n",
      "         Careers\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/contact\">\n",
      "         Contact\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/about/events\">\n",
      "         Events\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/site/glossary\">\n",
      "         Glossary\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/about/mission\">\n",
      "         Mission\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/news\">\n",
      "         News\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/people\">\n",
      "         People\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/about/using-our-images\">\n",
      "         Using Our Images\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/about/visitors\">\n",
      "         Visitors\n",
      "        </a>\n",
      "       </li>\n",
      "      </ul>\n",
      "     </li>\n",
      "     <li>\n",
      "      <a href=\"/facilities\">\n",
      "       Labs / Facilities\n",
      "      </a>\n",
      "      <ul>\n",
      "       <li>\n",
      "        <a href=\"/facilities/flynn-creek-crater-sample-collection\">\n",
      "         Flynn Creek Crater Sample Collection\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://www.moon-cal.org\">\n",
      "         Lunar Calibration Project\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/facilities/meteor-crater-sample-collection\">\n",
      "         Meteor Crater Sample Collection\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/facilities/mrctr\">\n",
      "         MRCTR GIS Lab\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/facilities/cartography-and-imaging-sciences-node-of-nasa-planetary-data-system\">\n",
      "         PDS Cartography and Imaging Sciences Node\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/pds/annex\">\n",
      "         PDS IMG Annex\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/facilities/photogrammetry-guest-facility\">\n",
      "         Photogrammetry Guest Facility\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/rpif\">\n",
      "         Regional Planetary Information Facility (RPIF)\n",
      "        </a>\n",
      "       </li>\n",
      "      </ul>\n",
      "     </li>\n",
      "     <li>\n",
      "      <a href=\"/maps\">\n",
      "       Maps / Products\n",
      "      </a>\n",
      "      <ul>\n",
      "       <li>\n",
      "        <a href=\"/search\">\n",
      "         Product Search\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://planetarynames.wr.usgs.gov\">\n",
      "         Gazetteer of Planetary Nomenclature\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://planetarymapping.wr.usgs.gov\">\n",
      "         Geologic Mapping Program\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://pilot.wr.usgs.gov\">\n",
      "         Planetary Image Locator Tool (PILOT)\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/search/planetary-index\">\n",
      "         Planetary Map Index\n",
      "        </a>\n",
      "       </li>\n",
      "      </ul>\n",
      "     </li>\n",
      "     <li>\n",
      "      <a href=\"/geology\">\n",
      "       Missions / Research\n",
      "      </a>\n",
      "      <ul>\n",
      "       <li>\n",
      "        <a href=\"/geology/mars-dunes\">\n",
      "         Mars Dunes\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/geology/mars-ice\">\n",
      "         Mars Ice\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/missions\">\n",
      "         Mission Support\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/solar-system\">\n",
      "         Solar System\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"/groups\">\n",
      "         Working Groups\n",
      "        </a>\n",
      "       </li>\n",
      "      </ul>\n",
      "     </li>\n",
      "     <li>\n",
      "      <a href=\"/tools\">\n",
      "       Tools\n",
      "      </a>\n",
      "      <ul>\n",
      "       <li>\n",
      "        <a href=\"http://planetarynames.wr.usgs.gov\">\n",
      "         Gazetteer of Planetary Nomenclature\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://isis.astrogeology.usgs.gov\">\n",
      "         Integrated Software for Imagers and Spectrometers (ISIS)\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://astrogeology.usgs.gov/tools/map-a-planet-2\">\n",
      "         Map a Planet 2\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://pilot.wr.usgs.gov\">\n",
      "         Planetary Image Locator Tool (PILOT)\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://astrocloud.wr.usgs.gov/\">\n",
      "         Projection on the Web (POW)\n",
      "        </a>\n",
      "       </li>\n",
      "      </ul>\n",
      "     </li>\n",
      "    </ul>\n",
      "    <form action=\"/search/results\" class=\"search\" id=\"search\" method=\"get\">\n",
      "     <input title=\"Search Astropedia\" type=\"submit\" value=\"\"/>\n",
      "     <input name=\"q\" placeholder=\"Search\" type=\"text\"/>\n",
      "     <input name=\"__ncforminfo\" type=\"hidden\" value=\"OqLN2n4INVgWXkvwWe5pxFxHctGsDA4J2BshN-XTjASZR_p0x8hoaebQU4JUrDSmgzOR-yGGWekzRYuMIM_oZhG2eJuvK-qAMxWdBYosAx8=\"/>\n",
      "    </form>\n",
      "   </nav>\n",
      "   <div class=\"container\">\n",
      "    <div class=\"widget block bar\">\n",
      "     <a href=\"/search\" style=\"float:left\">\n",
      "      <img alt=\"Astropedia\" src=\"/images/astropedia/astropedia-logo-main.png\" style=\"width:200px;border:none;\"/>\n",
      "      <h3>\n",
      "       Product Details\n",
      "      </h3>\n",
      "     </a>\n",
      "    </div>\n",
      "    <div class=\"wide-image-wrapper \" id=\"wide-image\">\n",
      "     <div class=\"downloads\">\n",
      "      <img class=\"thumb\" src=\"/cache/images/624683252b31408dabbc5c051b12a777_valles_marineris_unenhanced.tif_thumb.png\"/>\n",
      "      <h3>\n",
      "       Download\n",
      "      </h3>\n",
      "      <ul>\n",
      "       <li>\n",
      "        <a href=\"http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/valles_marineris_unenhanced.tif/full.jpg\" target=\"_blank\">\n",
      "         Sample\n",
      "        </a>\n",
      "        (jpg) 1024px wide\n",
      "       </li>\n",
      "       <li>\n",
      "        <a href=\"http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/valles_marineris_unenhanced.tif\" target=\"_blank\">\n",
      "         Original\n",
      "        </a>\n",
      "        (tif\n",
      "        <span class=\"tooltip word-tif\" title=\"\">\n",
      "        </span>\n",
      "        ) 24 MB\n",
      "       </li>\n",
      "      </ul>\n",
      "     </div>\n",
      "     <img class=\"wide-image\" src=\"/cache/images/8981a6d7057a7634dc312c0448f462c1_valles_marineris_unenhanced.tif_full.jpg\"/>\n",
      "     <a class=\"open-toggle\" href=\"#open\" id=\"wide-image-toggle\">\n",
      "      Open\n",
      "     </a>\n",
      "    </div>\n",
      "    <div class=\"content\">\n",
      "     <section class=\"block metadata\">\n",
      "      <a class=\"button\" href=\"/search/results?q=hemisphere+enhanced&amp;k1=target&amp;v1=Mars\">\n",
      "       Back\n",
      "      </a>\n",
      "      <h2 class=\"title\">\n",
      "       Valles Marineris Hemisphere Unenhanced\n",
      "      </h2>\n",
      "      <p>\n",
      "       Mosaic of the Valles Marineris hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. The distance is 2500 kilometers from the surface of the planet, with the scale being .6km/pixel. The mosaic is composed of 102 Viking Orbiter images of Mars. The center of the scene (lat -8, long 78) shows the entire Valles Marineris canyon system, over 2000 kilometers long and up to 8 kilometers deep, extending form Noctis Labyrinthus, the arcuate system of graben to the west, to the chaotic terrain to the east. Many huge ancient river channels begin from the chaotic terrain from north-central canyons and run north. The three Tharsis volcanoes (dark red spots), each about 25 kilometers high, are visible to the west. South of Valles Marineris is very ancient terrain covered by many impact craters.\n",
      "      </p>\n",
      "      <dl>\n",
      "       <dt>\n",
      "        Mimetype\n",
      "       </dt>\n",
      "       <dd>\n",
      "        <a href=\"/search/results?m=image/tiff\">\n",
      "         image/tiff\n",
      "        </a>\n",
      "       </dd>\n",
      "       <dt>\n",
      "        Filename\n",
      "       </dt>\n",
      "       <dd>\n",
      "        <a href=\"http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/valles_marineris_unenhanced.tif\">\n",
      "         valles_marineris_unenhanced.tif\n",
      "         <span class=\"tooltip word-tif\" title=\"\">\n",
      "         </span>\n",
      "        </a>\n",
      "       </dd>\n",
      "       <dt>\n",
      "        Originator\n",
      "       </dt>\n",
      "       <dd>\n",
      "       </dd>\n",
      "       <dt>\n",
      "        Group\n",
      "       </dt>\n",
      "       <dd>\n",
      "       </dd>\n",
      "       <dt>\n",
      "        Added to Astropedia\n",
      "       </dt>\n",
      "       <dd>\n",
      "        29 September 2011\n",
      "       </dd>\n",
      "       <dt>\n",
      "        Modified\n",
      "       </dt>\n",
      "       <dd>\n",
      "        3 November 2017\n",
      "       </dd>\n",
      "      </dl>\n",
      "      <h2>\n",
      "       General\n",
      "      </h2>\n",
      "      <dl>\n",
      "       <dt>\n",
      "        Geospatial Data Presentation Form\n",
      "       </dt>\n",
      "       <dd>\n",
      "        <a href=\"/search/results?k1=geospatial_data_presentation_form&amp;v1=Global+Mosaic\">\n",
      "         Global Mosaic\n",
      "        </a>\n",
      "       </dd>\n",
      "      </dl>\n",
      "      <h2>\n",
      "       Keywords\n",
      "      </h2>\n",
      "      <dl>\n",
      "       <dt>\n",
      "        Target\n",
      "       </dt>\n",
      "       <dd>\n",
      "        <a href=\"/search/results?k1=target&amp;v1=Mars\">\n",
      "         Mars\n",
      "        </a>\n",
      "       </dd>\n",
      "       <dt>\n",
      "        Theme\n",
      "       </dt>\n",
      "       <dd>\n",
      "        <a href=\"/search/results?k1=theme&amp;v1=Canyons\">\n",
      "         Canyons\n",
      "        </a>\n",
      "       </dd>\n",
      "       <dt>\n",
      "        Mission\n",
      "       </dt>\n",
      "       <dd>\n",
      "        <a href=\"/search/results?k1=mission&amp;v1=Viking+Orbiter\">\n",
      "         Viking Orbiter\n",
      "        </a>\n",
      "       </dd>\n",
      "      </dl>\n",
      "      <h2>\n",
      "       Geospatial Information\n",
      "      </h2>\n",
      "      <dl>\n",
      "       <dt>\n",
      "        Quad Name\n",
      "       </dt>\n",
      "       <dd>\n",
      "       </dd>\n",
      "      </dl>\n",
      "     </section>\n",
      "    </div>\n",
      "    <div class=\"sidebar\">\n",
      "     <div class=\"block\">\n",
      "      <h3 class=\"title\">\n",
      "       Related Products\n",
      "      </h3>\n",
      "      <a class=\"item\" href=\"/search/map/Mars/Viking/valles_marineris_enhanced\">\n",
      "       <img alt=\"Valles Marineris Hemisphere Enhanced thumbnail\" class=\"thumb description-thumb\" src=\"/cache/images/04085d99ec3713883a9a57f42be9c725_valles_marineris_enhanced.tif_thumb.png\"/>\n",
      "       <div class=\"description\">\n",
      "        <h3>\n",
      "         Valles Marineris Hemisphere Enhanced\n",
      "        </h3>\n",
      "        <p>\n",
      "         Mosaic of the Valles Marineris hemisphere of Mars projected into…\n",
      "        </p>\n",
      "       </div>\n",
      "      </a>\n",
      "      <a class=\"item\" href=\"/search/map/Mars/Viking/syrtis_major_unenhanced\">\n",
      "       <img alt=\"Syrtis Major Hemisphere Unenhanced thumbnail\" class=\"thumb description-thumb\" src=\"/cache/images/0039e532ab44f7836f8a384d6f9adc3f_syrtis_major_unenhanced.tif_thumb.png\"/>\n",
      "       <div class=\"description\">\n",
      "        <h3>\n",
      "         Syrtis Major Hemisphere Unenhanced\n",
      "        </h3>\n",
      "        <p>\n",
      "         Mosaic of the Syrtis Major hemisphere of Mars projected into point…\n",
      "        </p>\n",
      "       </div>\n",
      "      </a>\n",
      "      <a class=\"item\" href=\"/search/map/Mars/Viking/syrtis_major_enhanced\">\n",
      "       <img alt=\"Syrtis Major Hemisphere Enhanced thumbnail\" class=\"thumb description-thumb\" src=\"/cache/images/aae41197e40d6d4f3ea557f8cfe51d15_syrtis_major_enhanced.tif_thumb.png\"/>\n",
      "       <div class=\"description\">\n",
      "        <h3>\n",
      "         Syrtis Major Hemisphere Enhanced\n",
      "        </h3>\n",
      "        <p>\n",
      "         Mosaic of the Syrtis Major hemisphere of Mars projected into point…\n",
      "        </p>\n",
      "       </div>\n",
      "      </a>\n",
      "      <a class=\"item\" href=\"/search/map/Mars/Viking/schiaparelli_unenhanced\">\n",
      "       <img alt=\"Schiaparelli Hemisphere Unenhanced thumbnail\" class=\"thumb description-thumb\" src=\"/cache/images/eeda48b8f032727970d735b2b689937c_schiaparelli_unenhanced.tif_thumb.png\"/>\n",
      "       <div class=\"description\">\n",
      "        <h3>\n",
      "         Schiaparelli Hemisphere Unenhanced\n",
      "        </h3>\n",
      "        <p>\n",
      "         Mosaic of the Schiaparelli hemisphere of Mars projected into point…\n",
      "        </p>\n",
      "       </div>\n",
      "      </a>\n",
      "      <a class=\"item\" href=\"/search/map/Mars/Viking/schiaparelli_enhanced\">\n",
      "       <img alt=\"Schiaparelli Hemisphere Enhanced thumbnail\" class=\"thumb description-thumb\" src=\"/cache/images/7677c0a006b83871b5a2f66985ab5857_schiaparelli_enhanced.tif_thumb.png\"/>\n",
      "       <div class=\"description\">\n",
      "        <h3>\n",
      "         Schiaparelli Hemisphere Enhanced\n",
      "        </h3>\n",
      "        <p>\n",
      "         Mosaic of the Schiaparelli hemisphere of Mars projected into point…\n",
      "        </p>\n",
      "       </div>\n",
      "      </a>\n",
      "      <ul class=\"page-numbers\">\n",
      "       <li>\n",
      "        <a class=\"active \" href=\"/search/map/Mars/Viking/valles_marineris_unenhanced?p=1&amp;pb=1#downloads\">\n",
      "         1\n",
      "        </a>\n",
      "       </li>\n",
      "       <li>\n",
      "        <a class=\"\" href=\"/search/map/Mars/Viking/valles_marineris_unenhanced?p=2&amp;pb=1#downloads\">\n",
      "         2\n",
      "        </a>\n",
      "       </li>\n",
      "      </ul>\n",
      "     </div>\n",
      "    </div>\n",
      "   </div>\n",
      "   <div class=\"icons projects black scroll-wrapper\">\n",
      "    <div class=\"scroll\">\n",
      "     <a class=\"icon\" href=\"http://isis.astrogeology.usgs.gov\" title=\"Integrated Software for Imagers and Spectrometers\">\n",
      "      <img alt=\"ISIS Logo\" height=\"112\" src=\"/images/logos/isis_2x.jpg\" width=\"112\"/>\n",
      "      <span class=\"label\">\n",
      "       ISIS\n",
      "      </span>\n",
      "     </a>\n",
      "     <a class=\"icon\" href=\"http://planetarynames.wr.usgs.gov\" title=\"Gazetteer of Planetary Nomenclature\">\n",
      "      <img alt=\"Nomenclature Logo\" height=\"112\" src=\"/images/logos/nomenclature_2x.jpg\" width=\"112\"/>\n",
      "      <span class=\"label\">\n",
      "       Planetary Nomenclature\n",
      "      </span>\n",
      "     </a>\n",
      "     <a class=\"icon\" href=\"http://astrogeology.usgs.gov/tools/map\" title=\"Map a Planet 2\">\n",
      "      <img alt=\"Map-a-Planet Logo\" height=\"112\" src=\"/images/logos/map_a_planet_2x.jpg\" width=\"112\"/>\n",
      "      <span class=\"label\">\n",
      "       Map a Planet 2\n",
      "      </span>\n",
      "     </a>\n",
      "     <a class=\"icon\" href=\"/facilities/imaging-node-of-nasa-planetary-data-system-pds\" title=\"PDS Imaging Node\">\n",
      "      <img alt=\"PDS Logo\" height=\"112\" src=\"/images/pds_logo-black-web.png\"/>\n",
      "      <span class=\"label\">\n",
      "       PDS Imaging Node\n",
      "      </span>\n",
      "     </a>\n",
      "     <!--\n",
      "\t\t\t\t\t\t<a title=\"Astropedia Search\" href=\"/search\" class=\"icon\">\n",
      "\t\t\t\t\t\t\t<img alt=\"Astropedia Logo\" height=\"112\" width=\"112\" src=\"/images/logos/astropedia_2x.jpg\"/>\n",
      "\t\t\t\t\t\t\t<span class=\"label\">Astropedia</span>\n",
      "\t\t\t\t\t\t</a>\n",
      "-->\n",
      "     <a class=\"icon\" href=\"/rpif\" title=\"Regional Planetary Image Facility\">\n",
      "      <img alt=\"RPIF Logo\" height=\"112\" src=\"/images/logos/rpif_2x.jpg\" width=\"112\"/>\n",
      "      <span class=\"label\">\n",
      "       RPIF\n",
      "      </span>\n",
      "     </a>\n",
      "     <a class=\"icon\" href=\"/facilities/photogrammetry-guest-facility\" title=\"Photogrammetry Guest Facility\">\n",
      "      <img alt=\"Photogrammetry Guest Faciltiy Logo\" height=\"112\" src=\"/images/logos/photogrammetry_2x.jpg\" width=\"112\"/>\n",
      "      <span class=\"label\">\n",
      "       Photogrammetry Guest Facility\n",
      "      </span>\n",
      "     </a>\n",
      "     <a class=\"icon\" href=\"http://pilot.wr.usgs.gov\" title=\"Planetary Image Locator Tool\">\n",
      "      <img alt=\"Pilot Logo\" height=\"112\" src=\"/images/logos/pilot_2x.jpg\" width=\"112\"/>\n",
      "      <span class=\"label\">\n",
      "       PILOT\n",
      "      </span>\n",
      "     </a>\n",
      "     <a class=\"icon\" href=\"/facilities/mrctr\" title=\"Mapping, Remote-sensing, Cartography, Technology and Research GIS Lab\">\n",
      "      <img alt=\"MRCTR GIS Lab Logo\" height=\"112\" src=\"/images/logos/mrctr_2x.jpg\" width=\"112\"/>\n",
      "      <span class=\"label\">\n",
      "       MRCTR GIS Lab\n",
      "      </span>\n",
      "     </a>\n",
      "    </div>\n",
      "   </div>\n",
      "   <footer>\n",
      "    <div class=\"left\">\n",
      "     <a href=\"http://astrogeology.usgs.gov\">\n",
      "      Home\n",
      "     </a>\n",
      "     |\n",
      "     <a href=\"http://astrogeology.usgs.gov/contact\">\n",
      "      Contact\n",
      "     </a>\n",
      "     |\n",
      "     <a href=\"http://astrogeology.usgs.gov/about/events\">\n",
      "      Events\n",
      "     </a>\n",
      "     |\n",
      "     <a href=\"http://astrogeology.usgs.gov/news\">\n",
      "      News\n",
      "     </a>\n",
      "    </div>\n",
      "    <div class=\"right\">\n",
      "     <a href=\"http://www.doi.gov\">\n",
      "      U.S. Department of Interior\n",
      "     </a>\n",
      "     |\n",
      "     <a href=\"http://www.usgs.gov\">\n",
      "      U.S. Geological Survey\n",
      "     </a>\n",
      "     |\n",
      "     <a href=\"http://www.usa.gov\">\n",
      "      USA.gov\n",
      "     </a>\n",
      "    </div>\n",
      "   </footer>\n",
      "  </div>\n",
      "  <!--\n",
      "\t\t<div class=\"credit\">\n",
      "\t\t\t<small>Background Credits: NASA/USGS</small>\n",
      "\t\t</div>\n",
      "-->\n",
      "  <div class=\"page-background\" style=\"\n",
      "\t\t\tbackground:url('/images/backgrounds/mars.jpg');\n",
      "\t\t\tfilter:progid:DXImageTransform.Microsoft.AlphaImageLoader(\n",
      "\t\t\t\tsrc='/images/backgrounds/mars.jpg', sizingMethod='scale');\n",
      "\t\t\">\n",
      "  </div>\n",
      "  <script async=\"\" src=\"https://ssl.google-analytics.com/ga.js\" type=\"text/javascript\">\n",
      "  </script>\n",
      "  <script type=\"text/javascript\">\n",
      "   var baseUrl = \"\";\n",
      "\n",
      "\n",
      "var _gaq = _gaq || [];_gaq.push(['_setAccount', 'UA-27613186-1']);_gaq.push(['_trackPageview']);(function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();\n",
      "  </script>\n",
      "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\" type=\"text/javascript\">\n",
      "  </script>\n",
      "  <script src=\"//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js\" type=\"text/javascript\">\n",
      "  </script>\n",
      "  <script src=\"https://astropedia.astrogeology.usgs.gov/downloadWeb/dynamic/glossary.js\" type=\"text/javascript\">\n",
      "  </script>\n",
      "  <script src=\"/js/astro-tips.js\" type=\"text/javascript\">\n",
      "  </script>\n",
      "  <script src=\"/js/general.js\" type=\"text/javascript\">\n",
      "  </script>\n",
      "  <script type=\"text/javascript\">\n",
      "   /*&lt;![CDATA[*/\n",
      "showTooltips(\".downloads, .content dl, .listing\", true);\n",
      "/*]]&gt;*/\n",
      "  </script>\n",
      "  <div aria-live=\"assertive\" aria-relevant=\"additions\" class=\"ui-helper-hidden-accessible\" role=\"log\">\n",
      "  </div>\n",
      "  <div aria-live=\"assertive\" aria-relevant=\"additions\" class=\"ui-helper-hidden-accessible\" role=\"log\">\n",
      "  </div>\n",
      " </body>\n",
      "</html>\n"
     ]
    }
   ],
   "source": [
    "print(soup.prettify())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"NASA's Opportunity Rover Mission on Mars Comes to End\""
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "title_results = soup.find('div', class_='content_title')\n",
    "title = title_results.text.strip()\n",
    "title"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"NASA's Opportunity Mars rover mission is complete after 15 years on Mars. Opportunity's record-breaking exploration laid the groundwork for future missions to the Red Planet.\""
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "news_results = soup.find('div', class_='rollover_description_inner')\n",
    "news_p = news_results.text.strip()\n",
    "news_p"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "executable_path = {'executable_path': 'chromedriver.exe'}\n",
    "browser = Browser('chrome', **executable_path, headless=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "url = 'https://www.jpl.nasa.gov/spaceimages/index.php?category=Mars'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "background-image: url('/spaceimages/images/wallpaper/PIA19685-1920x1200.jpg');\n"
     ]
    }
   ],
   "source": [
    "browser.visit(url)\n",
    "for x in range(1):\n",
    "    html = browser.html\n",
    "    soup = BeautifulSoup(html, 'html.parser')\n",
    "    image = soup.find_all('article', class_='carousel_item')\n",
    "\n",
    "for i in image:\n",
    "    image_url = i['style']\n",
    "    print(i[\"style\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'InSight sol 99 (2019-03-07) low -95.8ºC (-140.4ºF) high -13.3ºC (8.1ºF)\\nwinds from the SW at 4.2 m/s (9.5 mph) gusting to 12.0 m/s (26.8 mph)\\npressure at 7.20 hPapic.twitter.com/XRi0faFSv5'"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "twitter_url = 'https://twitter.com/marswxreport?lang=en'\n",
    "browser.visit(twitter_url)\n",
    "html = browser.html\n",
    "soup = BeautifulSoup(html, 'html.parser')\n",
    "tweet_text = soup.find('p', class_='TweetTextSize TweetTextSize--normal js-tweet-text tweet-text')\n",
    "mars_weather = tweet_text.text.strip()\n",
    "mars_weather"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[                      0                              1\n",
       " 0  Equatorial Diameter:                       6,792 km\n",
       " 1       Polar Diameter:                       6,752 km\n",
       " 2                 Mass:  6.42 x 10^23 kg (10.7% Earth)\n",
       " 3                Moons:            2 (Phobos & Deimos)\n",
       " 4       Orbit Distance:       227,943,824 km (1.52 AU)\n",
       " 5         Orbit Period:           687 days (1.9 years)\n",
       " 6  Surface Temperature:                  -153 to 20 °C\n",
       " 7         First Record:              2nd millennium BC\n",
       " 8          Recorded By:           Egyptian astronomers]"
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "fact_url = 'https://space-facts.com/mars/'\n",
    "fact_tables = pd.read_html(fact_url)\n",
    "fact_tables"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Values</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Description</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Equatorial Diameter:</th>\n",
       "      <td>6,792 km</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Polar Diameter:</th>\n",
       "      <td>6,752 km</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Mass:</th>\n",
       "      <td>6.42 x 10^23 kg (10.7% Earth)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Moons:</th>\n",
       "      <td>2 (Phobos &amp; Deimos)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Orbit Distance:</th>\n",
       "      <td>227,943,824 km (1.52 AU)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Orbit Period:</th>\n",
       "      <td>687 days (1.9 years)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Surface Temperature:</th>\n",
       "      <td>-153 to 20 °C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>First Record:</th>\n",
       "      <td>2nd millennium BC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Recorded By:</th>\n",
       "      <td>Egyptian astronomers</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                             Values\n",
       "Description                                        \n",
       "Equatorial Diameter:                       6,792 km\n",
       "Polar Diameter:                            6,752 km\n",
       "Mass:                 6.42 x 10^23 kg (10.7% Earth)\n",
       "Moons:                          2 (Phobos & Deimos)\n",
       "Orbit Distance:            227,943,824 km (1.52 AU)\n",
       "Orbit Period:                  687 days (1.9 years)\n",
       "Surface Temperature:                  -153 to 20 °C\n",
       "First Record:                     2nd millennium BC\n",
       "Recorded By:                   Egyptian astronomers"
      ]
     },
     "execution_count": 42,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "fact_df = fact_tables[0]\n",
    "fact_df.columns = ['Description','Values']\n",
    "fact_df.set_index('Description', inplace=True)\n",
    "fact_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'<table border=\"1\" class=\"dataframe\">\\n  <thead>\\n    <tr style=\"text-align: right;\">\\n      <th></th>\\n      <th>Values</th>\\n    </tr>\\n    <tr>\\n      <th>Description</th>\\n      <th></th>\\n    </tr>\\n  </thead>\\n  <tbody>\\n    <tr>\\n      <th>Equatorial Diameter:</th>\\n      <td>6,792 km</td>\\n    </tr>\\n    <tr>\\n      <th>Polar Diameter:</th>\\n      <td>6,752 km</td>\\n    </tr>\\n    <tr>\\n      <th>Mass:</th>\\n      <td>6.42 x 10^23 kg (10.7% Earth)</td>\\n    </tr>\\n    <tr>\\n      <th>Moons:</th>\\n      <td>2 (Phobos &amp; Deimos)</td>\\n    </tr>\\n    <tr>\\n      <th>Orbit Distance:</th>\\n      <td>227,943,824 km (1.52 AU)</td>\\n    </tr>\\n    <tr>\\n      <th>Orbit Period:</th>\\n      <td>687 days (1.9 years)</td>\\n    </tr>\\n    <tr>\\n      <th>Surface Temperature:</th>\\n      <td>-153 to 20 °C</td>\\n    </tr>\\n    <tr>\\n      <th>First Record:</th>\\n      <td>2nd millennium BC</td>\\n    </tr>\\n    <tr>\\n      <th>Recorded By:</th>\\n      <td>Egyptian astronomers</td>\\n    </tr>\\n  </tbody>\\n</table>'"
      ]
     },
     "execution_count": 43,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "fact_html = fact_df.to_html()\n",
    "fact_html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [],
   "source": [
    "hemisphere_url = \"https://astrogeology.usgs.gov/search/results?q=hemisphere+enhanced&k1=target&v1=Mars\"\n",
    "hemisphere_titles = ['Cerberus Hemisphere','Schiaparelli Hemisphere','Syrtis Major Hemisphere','Valles Marineris Hemisphere']\n",
    "hemisphere_img_links = []\n",
    "browser.visit(hemisphere_url)\n",
    "for i in range(4):\n",
    "    html = browser.html\n",
    "    soup = BeautifulSoup(html, 'html.parser')\n",
    "    hemisphere_text = soup.find('a', class_='itemLink product-item')\n",
    "    browser.click_link_by_partial_text(hemisphere_titles[i])\n",
    "    hemisphere_url_2 = browser.url\n",
    "    browser.visit(hemisphere_url_2)\n",
    "    html = browser.html\n",
    "    soup = BeautifulSoup(html, 'html.parser')\n",
    "    hemisphere_img = soup.find_all('a', href=True)\n",
    "    img_links = []\n",
    "    for img in hemisphere_img:\n",
    "        img_links.append(img['href'])\n",
    "    hemisphere_img_links.append(img_links[41])\n",
    "    img_links[41]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/cerberus_enhanced.tif/full.jpg',\n",
       " 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/schiaparelli_unenhanced.tif/full.jpg',\n",
       " 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/syrtis_major_unenhanced.tif/full.jpg',\n",
       " 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/valles_marineris_unenhanced.tif/full.jpg']"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "hemisphere_img_links"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'title': 'Cerberus Hemisphere',\n",
       "  'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/cerberus_enhanced.tif/full.jpg'},\n",
       " {'title': 'Schiaparelli Hemisphere',\n",
       "  'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/schiaparelli_unenhanced.tif/full.jpg'},\n",
       " {'title': 'Syrtis Major Hemisphere',\n",
       "  'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/syrtis_major_unenhanced.tif/full.jpg'},\n",
       " {'title': 'Valles Marineris Hemisphere',\n",
       "  'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/valles_marineris_unenhanced.tif/full.jpg'}]"
      ]
     },
     "execution_count": 46,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "hemisphere_image_urls = [\n",
    "    {'title':hemisphere_titles[0],'img_url':hemisphere_img_links[0]},\n",
    "    {'title':hemisphere_titles[1],'img_url':hemisphere_img_links[1]},\n",
    "    {'title':hemisphere_titles[2],'img_url':hemisphere_img_links[2]},\n",
    "    {'title':hemisphere_titles[3],'img_url':hemisphere_img_links[3]}\n",
    "]\n",
    "hemisphere_image_urls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "scrape_mars = {\n",
    "    \"title\":title,\"paragraph\":news_p,\"featured_image\":image_url,\"weather\":mars_weather,\"table\":fact_html,\"hemisphere\":hemisphere_image_urls\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'title': \"NASA's Opportunity Rover Mission on Mars Comes to End\",\n",
       " 'paragraph': \"NASA's Opportunity Mars rover mission is complete after 15 years on Mars. Opportunity's record-breaking exploration laid the groundwork for future missions to the Red Planet.\",\n",
       " 'featured_image': \"background-image: url('/spaceimages/images/wallpaper/PIA19685-1920x1200.jpg');\",\n",
       " 'weather': 'InSight sol 99 (2019-03-07) low -95.8ºC (-140.4ºF) high -13.3ºC (8.1ºF)\\nwinds from the SW at 4.2 m/s (9.5 mph) gusting to 12.0 m/s (26.8 mph)\\npressure at 7.20 hPapic.twitter.com/XRi0faFSv5',\n",
       " 'table': '<table border=\"1\" class=\"dataframe\">\\n  <thead>\\n    <tr style=\"text-align: right;\">\\n      <th></th>\\n      <th>Values</th>\\n    </tr>\\n    <tr>\\n      <th>Description</th>\\n      <th></th>\\n    </tr>\\n  </thead>\\n  <tbody>\\n    <tr>\\n      <th>Equatorial Diameter:</th>\\n      <td>6,792 km</td>\\n    </tr>\\n    <tr>\\n      <th>Polar Diameter:</th>\\n      <td>6,752 km</td>\\n    </tr>\\n    <tr>\\n      <th>Mass:</th>\\n      <td>6.42 x 10^23 kg (10.7% Earth)</td>\\n    </tr>\\n    <tr>\\n      <th>Moons:</th>\\n      <td>2 (Phobos &amp; Deimos)</td>\\n    </tr>\\n    <tr>\\n      <th>Orbit Distance:</th>\\n      <td>227,943,824 km (1.52 AU)</td>\\n    </tr>\\n    <tr>\\n      <th>Orbit Period:</th>\\n      <td>687 days (1.9 years)</td>\\n    </tr>\\n    <tr>\\n      <th>Surface Temperature:</th>\\n      <td>-153 to 20 °C</td>\\n    </tr>\\n    <tr>\\n      <th>First Record:</th>\\n      <td>2nd millennium BC</td>\\n    </tr>\\n    <tr>\\n      <th>Recorded By:</th>\\n      <td>Egyptian astronomers</td>\\n    </tr>\\n  </tbody>\\n</table>',\n",
       " 'hemisphere': [{'title': 'Cerberus Hemisphere',\n",
       "   'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/cerberus_enhanced.tif/full.jpg'},\n",
       "  {'title': 'Schiaparelli Hemisphere',\n",
       "   'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/schiaparelli_unenhanced.tif/full.jpg'},\n",
       "  {'title': 'Syrtis Major Hemisphere',\n",
       "   'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/syrtis_major_unenhanced.tif/full.jpg'},\n",
       "  {'title': 'Valles Marineris Hemisphere',\n",
       "   'img_url': 'http://astropedia.astrogeology.usgs.gov/download/Mars/Viking/valles_marineris_unenhanced.tif/full.jpg'}]}"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "scrape_mars"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
